name: CI
on: [push, pull_request]

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@master
        
        - name: 'Login via Azure CLI'
          uses: Azure/docker-login@v1
          with:
              login-server: mitsha.azurecr.io
              username: ${{ SECRETS.REGISTRY_USERNAME }}
              password: ${{ SECRETS.REGISTRY_PASSWORD }}

        - run: |
            docker build . -t mitsha.azurecr.io/aci-up-java-example:${{ github.sha }}
            docker push mitsha.azurecr.io/aci-up-java-example:${{ github.sha }}

        - name: 'Azure Login'
          uses: azure/login@v1
          with:
            creds: ${{ SECRETS.AZURE_CREDENTIALS }}
        
        - name: 'Deploy to Azure Container Instances'
          uses: azure/CLI@v1
          with: 
            azcliversion: 2.0.77
            inlineScript: |
              az container create --resource-group mitsha-test --name aci-up-java-example --image mitsha.azurecr.io/aci-up-java-example:${{ github.sha }} --ports 80 5777 --dns-name-label aci-up-java-example --registry-username ${{ SECRETS.REGISTRY_USERNAME }} --registry-password ${{ SECRETS.REGISTRY_PASSWORD }}